name: Find changed tex files

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      # Checkout the repository content
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      # Get the list of changed .tex files
      - name: Get changed tex files
        id: changed-tex-files
        run: |
          echo "Changed tex files:"
          git diff --name-only origin/main -- docs/**/*.tex > changed_files.txt
          cat changed_files.txt

      # Compile each changed LaTeX file using latex-action
      - name: Compile changed LaTeX files
        run: |
          while IFS= read -r file; do
            echo "Compiling $file"
            gh workflow run 'Compile LaTeX Document' --ref ${{ github.head_ref }} \
            -f latexmk_options='-pdf -bibtex' \
            -f root_file=$file
          done < changed_files.txt
