name: 'Compile LaTeX Document'

on:
  push:
    branches: [main]
    paths:
      - 'docs/**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache TeX Live and latexmk installation
      - name: Cache TeX Live
        id: texlive-cache
        uses: actions/cache@v3
        with:
          path: /usr/local/texlive
          key: texlive-2023-ubuntu-latexmk
          restore-keys: |
            texlive-

      # Install TeX Live and latexmk if cache is not available
      - name: Install TeX Live and latexmk
        if: steps.texlive-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install texlive-latex-extra texlive-science latexmk

      # Get changed .tex files
      - name: Get changed .tex files
        id: changed-tex-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.tex
          diff_relative: true  # Get the list of files relative to the repo root

      # Build LaTeX files
      - name: Build changed tex files
        if: steps.changed-tex-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-tex-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            filename=$(basename -- "$file")
            folder=$(dirname "$file")  # Get the folder of the file
            echo "Building $filename"
            cd "$folder"  # Change to the folder where the tex file is located
            make 
            make clean
            cd -  # Go back to root folder
          done
          
      # Commit the generated PDF back to the repository
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${GH_TOKEN}
          message: 'Add compiled PDF for $(basename "${{ github.event.inputs.root_file }}").tex'
