name: 'Compile LaTeX Document'

on:
  push:
    branches: [main]
    paths:
      - 'docs/**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Tex Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-medium
            latexmk

      # Get changed .tex files
      - name: Get changed .tex files
        id: changed-tex-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.tex
          diff_relative: true  # Get the list of files relative to the repo root

      # Build LaTeX files
      - name: Build changed tex files
        if: steps.changed-tex-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-tex-files.outputs.all_changed_files }}
        run: |
          whereis latex
          whereis latexmk
          cd ~
          ls -a
          cd -
          for file in ${ALL_CHANGED_FILES}; do
            filename=$(basename -- "$file")
            folder=$(dirname "$file")  # Get the folder of the file
            echo "Building $filename"
            cd "$folder"  # Change to the folder where the tex file is located
            make 
            ls
            make clean
            ls
            cd -  # Go back to root folder
          done
          git status
          
      # Commit the generated PDF back to the repository
      - name: Commit & Push changes
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-tex-files.outputs.all_changed_files }}
        uses: EndBug/add-and-commit@v9
        with:
          add: --force docs/**/*.pdf
          author_name: "Github Action"
          author_email: "action@github.com"
          message: "Add compiled PDF"
