name: 'Format tex files'

on:
  push:
    branches: [main]
    paths:
      - 'docs/**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Install tex-fmt
        run: |
          sudo apt install cargo
          cargo install tex-fmt
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
    # Get changed .tex files
      - name: Get changed .tex files
        id: changed-tex-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.tex
          diff_relative: true  # Get the list of files relative to the repo root

      # Format LaTeX files
      - name: Format changed tex files
        if: steps.changed-tex-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-tex-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            tex-fmt $file
          done

      # Commit the formatted tex files back to the repository
      - name: Commit & Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: --force docs/**/*.pdf
          author_name: "Github Action"
          author_email: "action@github.com"
          message: "format changed .tex files"
